// This file is auto-generated by @hey-api/openapi-ts

export const CatEntitySchema = {
  type: 'object',
  properties: {
    id: {
      type: 'number',
      description: 'The cat id',
      example: 1,
    },
    name: {
      type: 'string',
      description: 'The cat name',
      example: 'Kitty',
    },
    sex: {
      type: 'string',
      description: 'The cat sex',
      example: 'MALE',
    },
    age: {
      type: 'number',
      description: 'The cat age',
      example: 1,
    },
    breed: {
      type: 'string',
      description: 'The cat breed',
      example: 'Persian',
    },
    color: {
      type: 'string',
      description: 'The cat color',
      example: 'White',
    },
    ownerId: {
      type: 'number',
      description: 'The cat owner id',
      example: 1,
    },
  },
  required: ['id', 'name', 'sex', 'age', 'breed', 'color', 'ownerId'],
} as const;

export const CreateCatDtoSchema = {
  type: 'object',
  properties: {
    name: {
      type: 'string',
      description: 'The cat name',
      example: 'Kitty',
    },
    sex: {
      type: 'string',
      description: 'The cat sex',
      example: 'MALE',
    },
    age: {
      type: 'number',
      description: 'The cat age',
      example: 1,
    },
    breed: {
      type: 'string',
      description: 'The cat breed',
      example: 'Persian',
    },
    color: {
      type: 'string',
      description: 'The cat color',
      example: 'White',
    },
    ownerId: {
      type: 'number',
      description: 'The cat owner id',
      example: 1,
    },
  },
  required: ['name', 'sex', 'age', 'breed', 'color', 'ownerId'],
} as const;

export const UpdateCatDtoSchema = {
  type: 'object',
  properties: {
    name: {
      type: 'string',
      description: 'The cat name',
      example: 'Kitty',
    },
    sex: {
      type: 'string',
      description: 'The cat sex',
      example: 'MALE',
    },
    age: {
      type: 'number',
      description: 'The cat age',
      example: 1,
    },
    breed: {
      type: 'string',
      description: 'The cat breed',
      example: 'Persian',
    },
    color: {
      type: 'string',
      description: 'The cat color',
      example: 'White',
    },
    ownerId: {
      type: 'number',
      description: 'The cat owner id',
      example: 1,
    },
  },
} as const;
