// This file is auto-generated by @hey-api/openapi-ts

export type CatEntity = {
  /**
   * The cat id
   */
  id: number;
  /**
   * The cat name
   */
  name: string;
  /**
   * The cat sex
   */
  sex: string;
  /**
   * The cat age
   */
  age: number;
  /**
   * The cat breed
   */
  breed: string;
  /**
   * The cat color
   */
  color: string;
  /**
   * The cat owner id
   */
  ownerId: number;
};

export type CreateCatDto = {
  /**
   * The cat name
   */
  name: string;
  /**
   * The cat sex
   */
  sex: string;
  /**
   * The cat age
   */
  age: number;
  /**
   * The cat breed
   */
  breed: string;
  /**
   * The cat color
   */
  color: string;
  /**
   * The cat owner id
   */
  ownerId: number;
};

export type UpdateCatDto = {
  /**
   * The cat name
   */
  name?: string;
  /**
   * The cat sex
   */
  sex?: string;
  /**
   * The cat age
   */
  age?: number;
  /**
   * The cat breed
   */
  breed?: string;
  /**
   * The cat color
   */
  color?: string;
  /**
   * The cat owner id
   */
  ownerId?: number;
};

export type GetCatsData = {
  body?: never;
  path?: never;
  query: {
    limit: number;
  };
  url: '/';
};

export type GetCatsResponses = {
  /**
   * This action returns all cats
   */
  200: Array<CatEntity>;
};

export type GetCatsResponse = GetCatsResponses[keyof GetCatsResponses];

export type CreateCatData = {
  body: CreateCatDto;
  path?: never;
  query?: never;
  url: '/';
};

export type CreateCatResponses = {
  /**
   * The record has been successfully created.
   */
  201: CatEntity;
};

export type CreateCatResponse = CreateCatResponses[keyof CreateCatResponses];

export type DeleteCatData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/{id}';
};

export type DeleteCatErrors = {
  /**
   * The record with the given id was not found.
   */
  404: unknown;
};

export type DeleteCatResponses = {
  /**
   * The record has been successfully deleted.
   */
  204: void;
};

export type DeleteCatResponse = DeleteCatResponses[keyof DeleteCatResponses];

export type GetCatsByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/{id}';
};

export type GetCatsByIdErrors = {
  /**
   * The record with the given id was not found.
   */
  404: unknown;
};

export type GetCatsByIdResponses = {
  /**
   * This action returns a cat by id
   */
  200: CatEntity;
};

export type GetCatsByIdResponse =
  GetCatsByIdResponses[keyof GetCatsByIdResponses];

export type UpdateCatData = {
  body: UpdateCatDto;
  path: {
    id: number;
  };
  query?: never;
  url: '/{id}';
};

export type UpdateCatErrors = {
  /**
   * The record with the given id was not found.
   */
  404: unknown;
};

export type UpdateCatResponses = {
  /**
   * The record has been successfully updated.
   */
  204: UpdateCatDto;
};

export type UpdateCatResponse = UpdateCatResponses[keyof UpdateCatResponses];

export type ClientOptions = {
  baseUrl: string;
};
