// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zCatEntity = z.object({
  id: z.number(),
  name: z.string(),
  sex: z.string(),
  age: z.number(),
  breed: z.string(),
  color: z.string(),
  ownerId: z.number(),
});

export const zCreateCatDto = z.object({
  name: z.string(),
  sex: z.string(),
  age: z.number(),
  breed: z.string(),
  color: z.string(),
  ownerId: z.number(),
});

export const zUpdateCatDto = z.object({
  name: z.string().optional(),
  sex: z.string().optional(),
  age: z.number().optional(),
  breed: z.string().optional(),
  color: z.string().optional(),
  ownerId: z.number().optional(),
});

export const zGetCatsResponse = z.array(zCatEntity);

export const zCreateCatResponse = zCatEntity;

export const zDeleteCatResponse = z.void();

export const zGetCatsByIdResponse = zCatEntity;

export const zUpdateCatResponse = zUpdateCatDto;
