// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { AppControllerGetHelloData, AppControllerCreateCatData, AppControllerCreateCatResponse, AppControllerDeleteCatData, AppControllerUpdateCatData, AppControllerUpdateCatResponse } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const appControllerGetHello = <ThrowOnError extends boolean = false>(options?: Options<AppControllerGetHelloData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
        url: '/',
        ...options
    });
};

export const appControllerCreateCat = <ThrowOnError extends boolean = false>(options: Options<AppControllerCreateCatData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AppControllerCreateCatResponse, unknown, ThrowOnError>({
        url: '/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const appControllerDeleteCat = <ThrowOnError extends boolean = false>(options: Options<AppControllerDeleteCatData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<unknown, unknown, ThrowOnError>({
        url: '/{id}',
        ...options
    });
};

export const appControllerUpdateCat = <ThrowOnError extends boolean = false>(options: Options<AppControllerUpdateCatData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<AppControllerUpdateCatResponse, unknown, ThrowOnError>({
        url: '/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};