// This file is auto-generated by @hey-api/openapi-ts

export type CreateCatDto = {
    /**
     * The cat name
     */
    name: string;
    /**
     * The cat sex
     */
    sex: string;
    /**
     * The cat age
     */
    age: number;
    /**
     * The cat breed
     */
    breed: string;
    /**
     * The cat color
     */
    color: string;
    /**
     * The cat owner id
     */
    ownerId: number;
};

export type UpdateCatDto = {
    /**
     * The cat name
     */
    name?: string;
    /**
     * The cat sex
     */
    sex?: string;
    /**
     * The cat age
     */
    age?: number;
    /**
     * The cat breed
     */
    breed?: string;
    /**
     * The cat color
     */
    color?: string;
    /**
     * The cat owner id
     */
    ownerId?: number;
};

export type AppControllerGetHelloData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type AppControllerGetHelloResponses = {
    200: unknown;
};

export type AppControllerCreateCatData = {
    body: CreateCatDto;
    path?: never;
    query?: never;
    url: '/';
};

export type AppControllerCreateCatResponses = {
    /**
     * The record has been successfully created.
     */
    201: CreateCatDto;
};

export type AppControllerCreateCatResponse = AppControllerCreateCatResponses[keyof AppControllerCreateCatResponses];

export type AppControllerDeleteCatData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/{id}';
};

export type AppControllerDeleteCatErrors = {
    /**
     * The record with the given id was not found.
     */
    404: unknown;
};

export type AppControllerDeleteCatResponses = {
    /**
     * The record has been successfully deleted.
     */
    200: unknown;
};

export type AppControllerUpdateCatData = {
    body: UpdateCatDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/{id}';
};

export type AppControllerUpdateCatErrors = {
    /**
     * The record with the given id was not found.
     */
    404: unknown;
};

export type AppControllerUpdateCatResponses = {
    /**
     * The record has been successfully updated.
     */
    200: UpdateCatDto;
};

export type AppControllerUpdateCatResponse = AppControllerUpdateCatResponses[keyof AppControllerUpdateCatResponses];

export type ClientOptions = {
    baseUrl: string;
};